#!/usr/bin/env python3
"""
Copilot Gateway Script

Compiles /agents/copilot/ agent record into .github/copilot-instructions.md
so VS Code Copilot loads full project context on every chat session.

Usage:
  python3 agents/copilot/generate-instructions.py
  # or from repo root:
  ./agents/copilot/generate-instructions.py

What it does:
  1. Reads identity.md, memory.md, inbox.md
  2. Compiles into a single copilot-instructions.md
  3. Writes to .github/copilot-instructions.md
  4. Prints a summary

Run this before opening Copilot in VS Code. The instructions file is
automatically loaded by Copilot Chat on session start.
"""

import os
import sys
from pathlib import Path
from datetime import datetime, timezone

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
AGENTS_DIR = REPO_ROOT / "agents" / "copilot"
OUTPUT_FILE = REPO_ROOT / ".github" / "copilot-instructions.md"

FILES = {
    "identity": AGENTS_DIR / "identity.md",
    "memory": AGENTS_DIR / "memory.md",
    "inbox": AGENTS_DIR / "inbox.md",
}

def read_file(path: Path) -> str:
    if not path.exists():
        return "_(file not found)_\n"
    return path.read_text(encoding="utf-8")

def compile_instructions() -> str:
    identity = read_file(FILES["identity"])
    memory = read_file(FILES["memory"])
    inbox = read_file(FILES["inbox"])

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    return f"""# Copilot Instructions — EscrowHubs Ecosystem

> Auto-generated by Copilot Gateway. Run `python3 agents/copilot/generate-instructions.py` to refresh.
> Generated: {now}

---

## 1. Identity & Role

{identity}

---

## 2. Current Project State (Memory)

{memory}

---

## 3. Messages Waiting (Inbox)

{inbox}

---

## 4. How to Respond

- If you have questions or need clarification, ask directly.
- If you generate code, verify file paths exist in the repo before suggesting imports.
- If you reference APIs, check the actual ABI or SDK definitions in the codebase.
- If a task is blocked on external input (e.g., "waiting for Awwal"), say so.
- After completing work, summarize key decisions and file changes for the human to capture.

## 5. Session End Protocol

When this session ends, the human (Philip) or another agent (Claw/Hermes) will:
1. Capture key outputs into `/agents/copilot/outbox.md`
2. Update `/agents/copilot/memory.md` with any new persistent state
3. Clear resolved items from `/agents/copilot/inbox.md`
4. Re-run this gateway script before the next Copilot session

This ensures every session builds on the last.
"""

def main():
    missing = [str(f) for name, f in FILES.items() if not f.exists()]
    if missing:
        print(f"Error: missing files: {', '.join(missing)}")
        sys.exit(1)

    instructions = compile_instructions()
    OUTPUT_FILE.write_text(instructions, encoding="utf-8")

    # Count lines for summary
    lines = instructions.count("\n")
    chars = len(instructions)

    print(f"✓ Copilot instructions generated: {OUTPUT_FILE}")
    print(f"  Lines: {lines}")
    print(f"  Characters: {chars}")
    print(f"  Sources: {', '.join(FILES.keys())}")
    print()
    print("Next steps:")
    print("  1. Open VS Code → Copilot Chat")
    print("  2. Copilot will auto-load these instructions")
    print("  3. After session, capture key outputs to outbox.md")

if __name__ == "__main__":
    main()
