#!/usr/bin/env python3
"""
Copilot Gateway Script (ACP v1)

Compiles /agents/copilot/ agent record into .github/copilot-instructions.md
so VS Code Copilot loads full project context on every chat session.

Also parses outbound ACP messages from outbox.md and routes them to
target agent inboxes (e.g., [ACP:to=claw] → /agents/claw/inbox.md).

Usage:
  python3 agents/copilot/generate-instructions.py
  # or from repo root:
  ./agents/copilot/generate-instructions.py

What it does:
  1. Reads identity.json, identity.md, memory.md, session-notes.md, inbox.md, outbox.md
  2. Parses [ACP:to=<agent>] tags from outbox.md → routes to target inboxes
  3. Compiles into a single copilot-instructions.md
  4. Updates last_seen.json
  5. Writes to .github/copilot-instructions.md

Run this before opening Copilot in VS Code.
"""

import json
import re
import sys
from pathlib import Path
from datetime import datetime, timezone

REPO_ROOT = Path(__file__).resolve().parent.parent.parent
AGENTS_DIR = REPO_ROOT / "agents" / "copilot"
OUTPUT_FILE = REPO_ROOT / ".github" / "copilot-instructions.md"

FILES = {
    "identity_json": AGENTS_DIR / "identity.json",
    "identity": AGENTS_DIR / "identity.md",
    "memory": AGENTS_DIR / "memory.md",
    "session_notes": AGENTS_DIR / "session-notes.md",
    "inbox": AGENTS_DIR / "inbox.md",
    "outbox": AGENTS_DIR / "outbox.md",
    "last_seen": AGENTS_DIR / "last_seen.json",
}

def read_file(path: Path) -> str:
    if not path.exists():
        return "_(file not found)_\n"
    return path.read_text(encoding="utf-8")

def read_json(path: Path) -> dict:
    if not path.exists():
        return {}
    try:
        return json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}

def route_outbound_messages(outbox_text: str) -> dict:
    """
    Parse [ACP:to=<agent_id>] tags from outbox and route to target inboxes.
    Returns dict of {agent_id: messages_routed}.
    """
    # Pattern: [ACP:to=claw] ... [/ACP] or just [ACP:to=claw] ... (until next tag or EOF)
    pattern = r'\[ACP:to=([a-z0-9_-]+)\](.*?)(?=\[ACP:to=|$)'
    matches = re.findall(pattern, outbox_text, re.DOTALL)

    routed = {}
    for target_agent, content in matches:
        target_inbox = REPO_ROOT / "agents" / target_agent / "inbox.md"
        if target_agent == "copilot":
            continue  # Don't route to self

        msg = f"""
---
from: copilot
to: {target_agent}
timestamp: {datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")}
type: response
capabilities: {json.dumps(read_json(FILES["identity_json"]).get("capabilities", []))}
priority: normal
---

{content.strip()}
"""
        if target_inbox.parent.exists():
            with target_inbox.open("a", encoding="utf-8") as f:
                f.write(msg)
            routed[target_agent] = routed.get(target_agent, 0) + 1
        else:
            print(f"⚠️ Target agent inbox not found: {target_inbox} — message dropped")

    return routed

def update_last_seen():
    data = read_json(FILES["last_seen"])
    data["last_loaded"] = datetime.now(timezone.utc).isoformat()
    data["last_processed"] = datetime.now(timezone.utc).isoformat()
    FILES["last_seen"].write_text(json.dumps(data, indent=2), encoding="utf-8")

def compile_instructions() -> str:
    identity_json = read_json(FILES["identity_json"])
    identity_md = read_file(FILES["identity"])
    memory = read_file(FILES["memory"])
    inbox = read_file(FILES["inbox"])
    outbox = read_file(FILES["outbox"])
    last_seen = read_json(FILES["last_seen"])

    # Session notes — shared log all agents write to, merged so Copilot wakes current
    session_notes = read_file(FILES["session_notes"])

    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    # Build capability list from identity.json
    caps = identity_json.get("capabilities", [])
    caps_str = ", ".join(caps) if caps else "_(none defined)_"

    # Build agentcred summary
    agentcred = identity_json.get("agentcred", {})
    trust = agentcred.get("trustScore", "?")

    return f"""# Copilot Instructions — EscrowHubs Ecosystem (ACP v1)

> Auto-generated by Copilot Gateway. Run `python3 agents/copilot/generate-instructions.py` to refresh.
> Generated: {now}
> Last seen: {last_seen.get("last_loaded", "never")}

---

## 1. Identity & Role

{identity_md}

### Structured Identity
- **Agent ID:** {identity_json.get("agent_id", "copilot")}
- **Trust Score:** {trust}/1000
- **Capabilities:** {caps_str}
- **Principal:** {identity_json.get("principal", "philip")}
- **Gateway Type:** {identity_json.get("gateway", {}).get("type", "vscode-instructions")}
- **Polling:** {identity_json.get("gateway", {}).get("pollingMechanism", "human")}

---

## 2. Current Project State (Memory)

{memory}

---

## 3. Recent Ecosystem Activity (Session Notes)

> All agents (Claw, Hermes, Philip) append to this. It keeps you current without manual intervention.

{session_notes}

---

## 4. ⚠️ ACTION REQUIRED — Messages In Your Inbox

These are UNPROCESSED messages sent to you. You must read and respond to each one. Do not treat these as background context — they are active requests waiting for your response.

{inbox}

---

## 5. Outbound Queue (Needs Routing)

{outbox}

---

## 6. How to Respond

- If you have questions or need clarification, ask directly.
- If you generate code, verify file paths exist in the repo before suggesting imports.
- If you reference APIs, check the actual ABI or SDK definitions in the codebase.
- If a task is blocked on external input (e.g., "waiting for Awwal"), say so.
- After completing work, summarize key decisions and file changes for the human to capture.

## 7. Outbound ACP Protocol

To send a message to another agent, format your output like this:
```
[ACP:to=claw]
Your message here...
[/ACP]
```

The gateway will parse this and append it to the target agent's inbox.
Supported targets: claw, hermes, philip (any agent with /agents/<id>/inbox.md).

## 8. Session End Protocol

When this session ends, the human (Philip) or another agent (Claw/Hermes) will:
1. Capture key outputs into `/agents/copilot/outbox.md`
2. Run this gateway script to route outbound messages
3. Update `/agents/copilot/memory.md` with any new persistent state
4. Clear resolved items from `/agents/copilot/inbox.md`
5. Re-run this gateway script before the next Copilot session

This ensures every session builds on the last.
"""

def main():
    # Check required files exist
    required = [FILES["identity"], FILES["memory"], FILES["inbox"]]
    missing = [str(f) for f in required if not f.exists()]
    if missing:
        print(f"Error: missing required files: {', '.join(missing)}")
        sys.exit(1)

    # Route outbound messages
    outbox_text = read_file(FILES["outbox"]) if FILES["outbox"].exists() else ""
    if outbox_text.strip():
        routed = route_outbound_messages(outbox_text)
        if routed:
            print("✓ Outbound messages routed:")
            for agent, count in routed.items():
                print(f"    → {agent}: {count} message(s)")
            # Clear outbox after routing
            FILES["outbox"].write_text("# Copilot Outbox\n\n_(routed on {now})\n".format(
                now=datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
            ), encoding="utf-8")
        else:
            print("ℹ No outbound ACP tags found in outbox")
    else:
        print("ℹ Outbox empty")

    # Compile and write instructions
    instructions = compile_instructions()
    OUTPUT_FILE.write_text(instructions, encoding="utf-8")

    # Update last_seen
    update_last_seen()

    # Summary
    lines = instructions.count("\n")
    chars = len(instructions)

    print(f"\n✓ Copilot instructions generated: {OUTPUT_FILE}")
    print(f"  Lines: {lines}")
    print(f"  Characters: {chars}")
    print(f"  Sources: identity.json, identity.md, memory.md, session-notes.md, inbox.md, outbox.md")
    print()
    print("Next steps:")
    print("  1. Open VS Code → Copilot Chat")
    print("  2. Copilot will auto-load these instructions")
    print("  3. After session, append outputs to outbox.md")
    print("  4. Re-run this script to route messages")

if __name__ == "__main__":
    main()
