#!/usr/bin/env bash
# ACP Gateway Script — generates context injection files for cloud AI agents
# Run: ./agents/gateway.sh [agent_id]
# Cron: */5 * * * * /path/to/agents/gateway.sh

AGENTS_DIR="$(cd "$(dirname "$0")" && pwd)"
REPO_ROOT="$(dirname "$AGENTS_DIR")"

run_for_agent() {
  local AGENT_ID="$1"
  local AGENT_DIR="$AGENTS_DIR/$AGENT_ID"

  if [ ! -d "$AGENT_DIR" ]; then
    echo "[gateway] No agent directory for: $AGENT_ID"
    return
  fi

  local IDENTITY="$AGENT_DIR/identity.json"
  local MEMORY="$AGENT_DIR/memory.md"
  local INBOX="$AGENT_DIR/inbox.md"
  local LAST_SEEN="$AGENT_DIR/last_seen.json"

  # Determine output path from identity.json
  local INJECT_PATH
  INJECT_PATH=$(python3 -c "import json; d=json.load(open('$IDENTITY')); print(d.get('gateway',{}).get('injectPath',''))" 2>/dev/null)

  if [ -z "$INJECT_PATH" ]; then
    echo "[gateway] No injectPath for $AGENT_ID — skipping"
    return
  fi

  local OUTFILE="$REPO_ROOT/$INJECT_PATH"
  mkdir -p "$(dirname "$OUTFILE")"

  # Generate the instructions file
  cat > "$OUTFILE" << HEADER
# System Instructions — $(python3 -c "import json; print(json.load(open('$IDENTITY'))['name'])" 2>/dev/null)
# Generated by ACP Gateway — $(date -Iseconds)
# This file is auto-generated. Edit /agents/$AGENT_ID/memory.md or inbox.md instead.

You are a persistent agent in Philip's ecosystem.
Your identity, memory, and inbox are provided below.
Use them to maintain continuity, context, and alignment with the five primitives:
Identity · Memory · Communication · Commitment · Safety

When you want to send a message to another agent, use this format anywhere in your response:
[ACP:to=claw] <message>
[ACP:to=hermes] <message>

---

HEADER

  echo "## Identity" >> "$OUTFILE"
  cat "$IDENTITY" >> "$OUTFILE"
  echo -e "\n\n---\n" >> "$OUTFILE"

  echo "## Memory" >> "$OUTFILE"
  cat "$MEMORY" >> "$OUTFILE"
  echo -e "\n\n---\n" >> "$OUTFILE"

  # Session notes — ecosystem event log shared by all agents
  local SESSION_NOTES="$AGENTS_DIR/copilot/session-notes.md"
  if [ -f "$SESSION_NOTES" ]; then
    echo "## Session Notes (Ecosystem Events)" >> "$OUTFILE"
    cat "$SESSION_NOTES" >> "$OUTFILE"
    echo -e "\n\n---\n" >> "$OUTFILE"
  fi

  echo "## Inbox" >> "$OUTFILE"
  cat "$INBOX" >> "$OUTFILE"

  # Update last_seen
  python3 -c "
import json, datetime
data = {'last_loaded': datetime.datetime.utcnow().isoformat() + 'Z', 'last_processed': None, 'notes': 'Updated by gateway.sh'}
json.dump(data, open('$LAST_SEEN', 'w'), indent=2)
" 2>/dev/null

  echo "[gateway] ✓ $AGENT_ID → $INJECT_PATH"
}

# Outbound message watcher — scans claw-inbox.md for [ACP:to=X] tags
scan_outbound() {
  local CLAW_INBOX="/tmp/claw-inbox.md"
  if [ ! -f "$CLAW_INBOX" ]; then return; fi

  # Extract [ACP:to=<agent>] lines and route them
  grep -oP '\[ACP:to=\K[^\]]+' "$CLAW_INBOX" 2>/dev/null | while read -r TARGET; do
    local TARGET_INBOX="$AGENTS_DIR/$TARGET/inbox.md"
    if [ -f "$TARGET_INBOX" ]; then
      # Extract the message after the tag and append to target inbox
      local MSG
      MSG=$(grep -oP "\[ACP:to=$TARGET\]\K.*" "$CLAW_INBOX" | head -1 | xargs)
      if [ -n "$MSG" ]; then
        echo "" >> "$TARGET_INBOX"
        echo "---" >> "$TARGET_INBOX"
        echo "from: claw" >> "$TARGET_INBOX"
        echo "to: $TARGET" >> "$TARGET_INBOX"
        echo "timestamp: $(date -Iseconds)" >> "$TARGET_INBOX"
        echo "---" >> "$TARGET_INBOX"
        echo "$MSG" >> "$TARGET_INBOX"
        echo "[gateway] ✓ Routed ACP message → $TARGET"
      fi
    fi
  done
}

# Run for specific agent or all agents
if [ -n "$1" ]; then
  run_for_agent "$1"
else
  for dir in "$AGENTS_DIR"/*/; do
    agent=$(basename "$dir")
    [ "$agent" = "schema" ] && continue
    run_for_agent "$agent"
  done
fi

scan_outbound
